runmode = "release"   # 开发模式, debug, release, test
addr = ":9972"
appid = ""
apikey= ""

[db]
    [db.master]
        host = "127.0.0.1"
        port = 5432
        dbname = "test"
        user = "test"
        password = "test"

[redis]
    [redis.game]
        addr = "127.0.0.1:6379"
        db = 1
        password = "test"